services:
  - type: web
    name: prok-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: ALLOWED_ORIGINS
        value: http://localhost:5173,http://127.0.0.1:5173,https://prok-frontend-e44d.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
    build:
      cwd: app/backend
    start:
      cwd: app/backend
    healthCheckPath: /health

  - type: web
    name: prok-frontend
    env: static
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://prok-backend-ix6a.onrender.com
    build:
      cwd: app/frontend
    staticPublish:
      cwd: app/frontend 