services:
  - type: web
    name: prok-backend
    env: python
    pythonVersion: 3.10.12
    plan: free
    buildCommand: "bash build.sh"
    # Use the full module path so gunicorn works regardless of working directory.
    # This works from repo root, app/, or app/backend/ as long as PYTHONPATH is set (Render default).
    # If you get ModuleNotFoundError, check the working directory and use the correct module path.
    startCommand: "gunicorn backend.main:app --bind 0.0.0.0:$PORT --timeout 180"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://prok-frontend-e44d.onrender.com,http://localhost:5173
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.12
    build:
      cwd: app/backend
    start:
      cwd: app/backend
    healthCheckPath: /health

  - type: web
    name: prok-frontend
    env: static
    plan: free
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://prok-backend-ix6a.onrender.com
    build:
      cwd: app/frontend
    staticPublish:
      cwd: app/frontend 