"""Add advanced post fields for filtering and sorting

Revision ID: 4cb1c53cba5d
Revises: a89ded474300
Create Date: 2025-07-12 17:58:15.468528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cb1c53cba5d'
down_revision = 'a89ded474300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('views_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comments_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('media_url',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('media_type',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('media_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('media_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('comments_count')
        batch_op.drop_column('views_count')
        batch_op.drop_column('likes_count')
        batch_op.drop_column('visibility')
        batch_op.drop_column('tags')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
